##
## EPITECH PROJECT, 2022
## Makefile
## File description:
## Makefile
##

NAME	=	groundhog

$(NAME)	:
			cp ./src/groundhog.py .
			mv groundhog.py groundhog
			chmod +x groundhog

all	:	$(NAME)

clean:
		rm groundhog

fclean:	clean

re:	fclean all